services:
  source_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: source_db
    ports:
      - "5434:5432"  # Exposed for external access
    volumes:
      - ./source-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_replication_slots=2", "-c", "max_wal_senders=2", "-c", "listen_addresses=*"]
    networks:
      - replication_net

networks:
  replication_net:
    external: true